# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Meetup on Human Centered Computing"
email: "hmitre@cimat.mx"
description: "El Meetup de Computación Centrada en el Humano es un conjunto de conferencias y talleres organizados por el laboratorio de Computación Centrada en el Humano del Centro de Investigación en Matemáticas, A.C. (CIMAT), Unidad Zacatecas."
baseurl: "/"
url: "https://hcc-cimat.github.io"
permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "HCC Lab"
organizerAlternateName: "CIMAT Unidad Zacatecas"
organizerDescription: "Laboratorio de Computación Centrada en el Humano."
organizerEmail: "hmitre@cimat.mx"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://hcc-cimat.github.io/meetup"

# Head
metaKeywords: "event, programming, developers, university, startup, public servers"
twitterAccount: "@MeetupHCC"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "http://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Inicio"}
 - {permalink: "/noticias/", text: "Noticias"}
 - {permalink: "/programa/", text: "Programa"}
 - {permalink: "/ponentes/", text: "Ponentes"}
 - {permalink: "/staff/", text: "Staff"}
bottomNavigationLinks:
 - {permalink: "/registro", text: "Regístrate"}
rightNavigationButtons:
 - {permalink: "/registro", text: "Regístrate"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Meetup HCC-CIMAT. <br>Hecho para <typeout>"
eventDate: "16-17 Agosto, 2018. Entrada libre."
typeoutTextValues: '"", "universitarios.", "investigadores.", "líderes funcionarios.", "empresarios."'
typeoutFallback: ""
heroButtons:
 - {permalink: "/registro", text: "Regístrate"}

# About Block
aboutTitle: "Acerca del Meetup"
aboutBlock:
 - {title: "Conferencias", image: "conference.jpg", text: "Estudiantes e investigadores compartirán investigaciones de punta." }
 - {title: "Talleres", image: "workshop.jpg", text: "Aprende a utilizar rastreadores oculares y armar tus propias redes neuronales." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "15", specialCharacter: "~", info: "Participantes", detail: "¡En talleres prácticos!"}
 - {count: "60", specialCharacter: "~", info: "Asistentes", detail: "¡En total para el evento!"}
 - {count: "13", specialCharacter: "+", info: "Horas", detail: "¡De conferecias y talleres!"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Ponentes"
rockstarSpeakersButtonText: "Ver todos los ponentes"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Centro de Investigación en Matemáticas, A.C. (CIMAT) Unidad Zacatecas"
eventLocationLink: "http://www.ingsoft.mx/"
eventStreetAddress: "Avenida Lasec Andador Galileo Galilei, Manzana 3 Lote 7"
eventAddressLocality: "Zacatecas"
eventAddressLocalityRegion: "Zac."
eventPostalCode: "98160"
eventAddressCountry: "México"
eventStartTime: "2018-08-16T9:00"
eventDoorTime: "09:00"
eventEndTime: "2018-08-17T16:00"
eventPlaceCoordinates: "22.7860891, -102.6161386"
mapCenterCoordinates: "22.7860891, -102.6161386"
mapMobileCenterCoordinates: "22.7860891, -102.6161386"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Computación Centrada en el Humano: "
twitterHashTag: "MeetupHCC"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Creado por"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Conviértete en sponsor"

# Footer
socialLinks:
 - {link: "https://github.com/HCC-CIMAT/", icon: "github"}
 - {link: "https://twitter.com/MeetupHCC", icon: "twitter"}
 - {link: "https://www.facebook.com/cimatzac/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.ingsoft.mx/", text: "Grupo de Ingeniería de Software, CIMAT"}
   - {link: "https://cimat.mx/", text: "Centro de Investigación en Matemáticas, A.C."}
 -
  title: "Contacto"
  links:
   - {link: "mailto:hmitre@cimat.mx", text: "hmitre@cimat.mx"}
 # -
 #  title: "FAQ"
 #  links:
 #   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Acerca del evento"
aboutUs: "El Meetup de Computación Centrada en el Humano es un conjunto de conferencias y talleres organizados por el laboratorio de Computación Centrada en el Humano del Centro de Investigación en Matemáticas, A.C. (CIMAT), Unidad Zacatecas."
